r"""P3 (b) — the gradient face: the multipole fringe, and the quadrupole wedge.

A pole face terminates whatever multipole the body carries, not only its dipole
component. P2 (i) gave the face its *dipole* fringe and P3 (a) gave it its *rotation*;
this file is the ``k1`` half — the piece a plain :class:`~accsim.Quadrupole` needs (its
own faces were not modelled at all) and the piece on which ``Dipole(fringe=True, k1=...)``
refused until now.

**The gate structure here is upside-down from every milestone before it**, and that is
the reason this file is shaped the way it is. The gradient fringe is a *cubic* point
transformation, so:

- ``matrix``, the tunes, ``beta``, the dispersion, the chromaticity **and the whole
  second-order map of** :mod:`accsim.taylor` are blind to it. MAD-X's ``sectormap`` and
  PTC at ``no = 2`` — the arbiters that carried P1, P2 and P3 (a) — would pass a map
  that did nothing at all. Writing that comparison here would be a *vacuous* gate.
- it is exactly **linear in** ``k1`` and exactly **cubic in the amplitude**, so the
  ``k1`` scaling and the amplitude order both have unit slope for *any* coefficient;
- it is generated by an F2, so symplecticity is exact by construction for any
  coefficient too.

So a uniform mis-scale of the ``1/12`` passes every structural gate in the project. That
is J1's lesson verbatim, and the answer is the one CLAUDE.md prescribes: the coefficient
is **derived**, from Maxwell and the Lorentz force, in the first two tests below. The
derivation shares no arithmetic with the code and no constant with either reference code,
and it fixes the entrance sign as well as the size.

The **quadrupole wedge** is the other half of a *rotated* gradient face, and it is
different physics: quadratic, not cubic, so it is the one piece here that does move the
second-order map — which is a gain, since it hands the second-order arbiters back.
"""

from __future__ import annotations

import numpy as np
import pytest
import sympy as sp

from accsim import (
    Dipole,
    Drift,
    Lattice,
    Quadrupole,
    ReferenceParticle,
    closed_twiss,
    is_symplectic_map_canonical,
    jacobian,
    natural_chromaticity,
    taylor_expand,
    tunes,
)
from accsim.coords import DELTA, DIM, PX, PY, X, Y
from accsim.elements.dipole import curvature_sextupole_kick, hard_edge_fringe_map, wedge_map
from accsim.elements.fringe import multipole_fringe_map, quad_wedge_map

MASS0, GAMMA0 = 938.27208816e6, 20.0

#: Every coordinate live at once. The fringe's entries are products of three coordinates,
#: so a state with a zero in it cannot separate one term from another; ``delta`` is out at
#: a few percent because the whole map carries ``1/(1+delta)`` factors.
STATES = [
    np.array([3.0e-3, 1.1e-3, -2.0e-3, 7.0e-4, 1.0e-3, 2.0e-3]),
    np.array([-5.0e-3, 2.0e-3, 4.0e-3, -1.5e-3, -1.0e-3, 3.0e-2]),
    np.array([8.0e-3, -4.0e-3, 6.0e-3, 9.0e-3, 3.0e-3, -2.0e-2]),
]


@pytest.fixture
def ref() -> ReferenceParticle:
    return ReferenceParticle.from_gamma(MASS0, GAMMA0)


@pytest.fixture
def slow_ref() -> ReferenceParticle:
    """A low-energy reference — the ``zeta`` term carries ``E/E0``, which is ``1`` to
    within every transverse tolerance at ``gamma0 = 20``. P2 (i)'s finding, one map over.
    """
    return ReferenceParticle.from_gamma(MASS0, 1.5)


# ---------------------------------------------------------------------------
# The derivation. Step 1: Maxwell fixes the 12.
# ---------------------------------------------------------------------------


def test_maxwell_fixes_the_twelve() -> None:
    r"""A quadrupole with a longitudinal profile is **not** ``g(s)`` times the 2D field.

    ``grad^2 psi = 0`` will not allow it: the ``g''`` the profile introduces has to be
    absorbed by a transverse term one order higher in the radius. For a 2D harmonic ``u``
    of degree ``N``,

        grad_perp^2 (r^2 u) = 4 (N + 1) u      [Euler: x d_x + y d_y = N on u]

    so ``psi = g u - g'' r^2 u / (4(N+1)) + O(g'''')`` is the unique continuation whose
    on-axis expansion coefficients are the derivatives of ``g`` — the generalised-gradient
    form MAD-NG and PTC both assume, and the one a real magnet with distant sources has.

    A quadrupole is ``N = 2``, giving ``-1/12``. **That is the 12 in the shipped map**,
    and nothing in the code below is consulted to get it. The dipole's ``N = 1`` and the
    sextupole's ``N = 3`` are checked alongside, because a coefficient that came out right
    for one degree by accident would not stay right across three.
    """
    x, y, s, c1 = sp.symbols("x y s c1", real=True)
    g = sp.Function("g")(s)

    for degree, u in ((1, y), (2, x * y), (3, 3 * x**2 * y - y**3)):
        assert sp.simplify(sp.diff(u, x, 2) + sp.diff(u, y, 2)) == 0, "u must be harmonic"
        psi = g * u + c1 * sp.diff(g, s, 2) * (x**2 + y**2) * u
        lap = sp.expand(sp.diff(psi, x, 2) + sp.diff(psi, y, 2) + sp.diff(psi, s, 2))
        solved = sp.solve(sp.Eq(lap.coeff(sp.diff(g, s, 2)), 0), c1)
        assert solved == [sp.Rational(-1, 4 * (degree + 1))], degree

    quad_c1 = sp.Rational(-1, 4 * (2 + 1))
    assert quad_c1 == sp.Rational(-1, 12)


# ---------------------------------------------------------------------------
# The derivation. Step 2: the Lorentz force turns it into a map.
# ---------------------------------------------------------------------------


#: Two longitudinal ramps on ``[-l, l]``, rising ``0 -> 1``. Both are **C^2** at the
#: joins, and that is a physical requirement, not neatness: the harmonic completion puts a
#: ``g''`` term in the *transverse* field, so a profile whose ``g''`` jumps at the matching
#: plane does not hand back the plain 2D field there and is not comparable with the
#: hard-edge model at all. (A C^1-only ramp was tried and gives a momentum kick of exactly
#: zero — a clean way to lose the whole effect.) Beyond that the shapes are unrelated: the
#: hard-edge answer must not know which one it came from, because only the *moments*
#: ``int g' = 1`` and ``int s g'' = -1`` survive ``l -> 0``. Running the derivation twice
#: is what says so.
def _profile(s: sp.Symbol, half_width: sp.Symbol, index: int) -> sp.Expr:
    u = (s + half_width) / (2 * half_width)
    smoothstep = 10 * u**3 - 15 * u**4 + 6 * u**5
    return [smoothstep, smoothstep + 5 * u**3 * (1 - u) ** 3][index]


def _lorentz_fringe(profile_index: int, *, switching_off: bool) -> dict[str, sp.Expr]:
    r"""The hard-edge fringe of a ``k1`` face, from the field alone.

    Field: ``b = -grad psi`` with ``psi`` the harmonically-completed profile of the first
    test. Motion: ``dpx/ds = y' b_s - b_y`` and ``dpy/ds = b_x - x' b_s`` — exact for a
    straight reference frame, evaluated to **first order in** ``k1`` along the unperturbed
    straight line, which is all the map has (it is exactly linear in ``k1``).

    The fringe map is what is left after the **hard-edge model's own** integral is
    subtracted and the extent ``l -> 0``. Two things survive that limit, and which is
    which is the physics:

    - ``b_s = -g' u`` is ``O(1/l)`` over a range ``O(l)``, so it gives the **momentum**
      kick directly, through ``int g' = 1``;
    - the ``g''`` term of the completed potential is ``O(1/l^2)``, so integrated once it
      makes ``px`` deviate by ``O(1/l)`` *inside* the fringe, and that deviation
      integrated over the extent leaves a finite **position** shift. That is where
      ``x -> x + kappa (x^3 + 3xy^2)/12`` comes from — a map that was a pure momentum
      kick would have missed it, and would not have been symplectic.

    Both position integrals are written with the order of integration swapped,
    ``int ds int_lo^s f dt = int f(t) (hi - t) dt``, which turns a nested sympy
    ``integrate`` into a single one and the runtime from minutes into seconds.
    """
    x0, y0, xp, yp, delta, k1 = sp.symbols("x0 y0 xp yp delta k1", real=True)
    s = sp.Symbol("s", real=True)
    half = sp.Symbol("half", positive=True)
    xx, yy = sp.symbols("xx yy", real=True)

    g = _profile(s, half, profile_index)
    if switching_off:
        g = g.subs(s, -s)  # the same ramp reversed: the field is on *before* this face

    u2d = -k1 * xx * yy  # b = -grad psi  ->  (b_x, b_y) = (k1 y, k1 x)
    psi = g * u2d - sp.diff(g, s, 2) * (xx**2 + yy**2) * u2d / 12
    b = (-sp.diff(psi, xx), -sp.diff(psi, yy), -sp.diff(psi, s))
    b_hard = (k1 * yy, k1 * xx, sp.Integer(0))  # the plain 2D field, body side only

    lo_h = -half if switching_off else sp.Integer(0)
    hi_h = sp.Integer(0) if switching_off else half
    traj = {xx: x0 + xp * s, yy: y0 + yp * s}
    force = [sp.expand((yp * b[2] - b[1]).subs(traj)), sp.expand((b[0] - xp * b[2]).subs(traj))]
    force_h = [
        sp.expand((yp * b_hard[2] - b_hard[1]).subs(traj)),
        sp.expand((b_hard[0] - xp * b_hard[2]).subs(traj)),
    ]

    def _integrate(f: sp.Expr, lo: sp.Expr, hi: sp.Expr, weight: sp.Expr | None = None) -> sp.Expr:
        return sp.integrate(f if weight is None else sp.expand(f * weight), (s, lo, hi))

    kick = [_integrate(force[i], -half, half) - _integrate(force_h[i], lo_h, hi_h) for i in (0, 1)]
    shift = [
        (_integrate(force[i], -half, half, half - s) - _integrate(force_h[i], lo_h, hi_h, hi_h - s))
        / (1 + delta)
        for i in (0, 1)
    ]

    eps = sp.Symbol("eps", positive=True)
    scale = {x0: eps * x0, y0: eps * y0, xp: eps * xp, yp: eps * yp}

    def _cubic(expr: sp.Expr) -> sp.Expr:
        limited = sp.limit(sp.cancel(sp.expand(expr)), half, 0)
        return sp.expand(sp.expand(limited).subs(scale)).coeff(eps, 3)

    return {
        "px": _cubic(kick[0]),
        "py": _cubic(kick[1]),
        "x": _cubic(shift[0]),
        "y": _cubic(shift[1]),
    }


def _shipped_first_order(switching_off: bool) -> dict[str, sp.Expr]:
    """The shipped map's own displacements, expanded to first order in ``k1``.

    Symbols, not floats — so the comparison against the derivation is an identity in
    ``(x, y, x', y', delta)``, not an agreement at a handful of sampled amplitudes.
    """
    x0, y0, xp, yp, delta, k1 = sp.symbols("x0 y0 xp yp delta k1", real=True)
    kappa = -k1 if switching_off else k1
    rpp = 1 / (1 + delta)
    fx = -kappa * (x0**3 + 3 * x0 * y0**2) / 12
    fy = kappa * (3 * x0**2 * y0 + y0**3) / 12
    # px = (1 + delta) x' is the paraxial identification the derivation's x' makes.
    px, py = xp * (1 + delta), yp * (1 + delta)
    fxx, fxy = sp.diff(fx, x0), sp.diff(fx, y0)
    fyx, fyy = sp.diff(fy, x0), sp.diff(fy, y0)
    return {
        "x": -fx * rpp,
        "y": -fy * rpp,
        "px": fxx * rpp * px + fyx * rpp * py,
        "py": fxy * rpp * px + fyy * rpp * py,
    }


def _identical(a: sp.Expr, b: sp.Expr) -> bool:
    """``a == b`` as rational functions — cleared of the common ``1/(1+delta)`` first."""
    delta = sp.Symbol("delta", real=True)
    return sp.expand(sp.cancel((a - b) * (1 + delta))) == 0


@pytest.mark.parametrize("profile_index", [0, 1])
def test_the_lorentz_integral_through_a_vanishing_fringe_is_the_shipped_map(
    profile_index: int,
) -> None:
    r"""The whole map, derived from the field — coefficient, structure and **sign**.

    This is the gate the milestone actually rests on. Everything else in the file passes
    for a map whose ``1/12`` is any other number; this one does not, and it reaches the
    answer through Maxwell and the Lorentz force without consulting xtrack, MAD-NG or the
    shipped code.

    Run for **two different ramps**, which is the statement that the hard-edge limit is
    profile-independent — the physical content of calling it a *hard-edge* fringe.
    """
    derived = _lorentz_fringe(profile_index, switching_off=False)
    shipped = _shipped_first_order(switching_off=False)
    for key in ("x", "y", "px", "py"):
        assert _identical(derived[key], shipped[key]), key


def test_the_exit_face_is_the_same_derivation_with_the_field_switching_off() -> None:
    r"""``kappa`` flips sign at the exit, and the derivation says so rather than the code.

    An exit-face sign error is **partially self-cancelling** — with both faces on, the
    wrong sign changes the magnitude but leaves the structure intact — so it is the error
    least likely to be caught by a whole-element comparison. Here the field ramps *down*
    across the face instead of up, ``int g'`` becomes ``-1``, and every displacement
    reverses. Nothing else about the derivation changes.
    """
    derived = _lorentz_fringe(0, switching_off=True)
    shipped = _shipped_first_order(switching_off=True)
    for key in ("x", "y", "px", "py"):
        assert _identical(derived[key], shipped[key]), key

    entry = _shipped_first_order(False)
    assert all(_identical(shipped[k], -entry[k]) for k in ("x", "y", "px", "py"))


# ---------------------------------------------------------------------------
# Symplecticity — exact by construction, so a transcription slip is what it catches
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("state", STATES)
def test_the_map_is_exactly_symplectic_at_amplitude(state: np.ndarray, ref) -> None:
    """Not symplectic *to the order written* — symplectic, because it is an F2.

    Both faces, and the elements that compose them. The gate cannot see the ``1/12``
    (any coefficient generates a symplectic map), but it sees any slip in the
    inverse-transpose momentum rule or in the ``zeta`` term, which are conjugate halves
    of the same generating function.
    """
    for exit_face in (False, True):
        assert is_symplectic_map_canonical(
            lambda s, e=exit_face: multipole_fringe_map(s, 1.7, ref, exit_face=e), state, ref
        )
    assert is_symplectic_map_canonical(
        lambda s: Quadrupole(0.6, 1.3, fringe=True).track(s, ref), state, ref
    )
    assert is_symplectic_map_canonical(
        lambda s: Dipole(1.0, 0.3, k1=0.4, e1=0.08, e2=0.05, fringe=True).track(s, ref),
        state,
        ref,
    )


def test_the_time_term_is_the_generating_functions_own() -> None:
    r"""``zeta``'s share, derived from the F2 rather than compared against a reference.

    It is the half of the map **no** reference leg in this milestone can see. The xtrack
    comparison runs at ``gamma0 = 20``, where ``E/E0`` and ``1`` differ by less than every
    tolerance in the file; ``sectormap`` and PTC at ``no = 2`` cannot see a cubic term at
    all. P2 (i) hit exactly this and reached for symplecticity — which works there because
    the dipole fringe's ``zeta`` term is comparable in size to its transverse ones. Here it
    is not: the whole map is cubic, so a 0.1% error in ``zeta`` is a ``5e-14`` perturbation
    of a Poisson bracket, and a finite-difference symplecticity check does **not** resolve
    it. (Measured — the variant with the factor dropped passes
    :func:`~accsim.is_symplectic_map_canonical` at ``gamma0 = 1.5``.)

    So it is derived instead, and exactly. With ``tau = zeta/beta0`` conjugate to
    ``p_tau``, the map is generated by ``F2 = P . g(q, p_tau) + tau p_tau'`` with
    ``g = q - f(q)/(1 + delta)``; reading ``T = dF2/dp_tau`` and using
    ``ddelta/dp_tau = (1/beta0 + p_tau)/(1 + delta)`` gives

        zeta -> zeta + (1 + beta0 p_tau) (P . f)/(1 + delta)^3,

    and ``1 + beta0 p_tau`` **is** ``E/E0``. That is the shipped line, factor for factor.
    """
    x, y, px, py, ptau, k1, beta0 = sp.symbols("x y px py ptau k1 beta0", real=True)
    delta = sp.sqrt(1 + 2 * ptau / beta0 + ptau**2) - 1
    rpp = 1 / (1 + delta)

    fx = -k1 * (x**3 + 3 * x * y**2) / 12
    fy = k1 * (3 * x**2 * y + y**3) / 12
    gx, gy = x - fx * rpp, y - fy * rpp

    jac = sp.Matrix([[sp.diff(gx, x), sp.diff(gx, y)], [sp.diff(gy, x), sp.diff(gy, y)]])
    big_p = jac.T.inv() * sp.Matrix([px, py])  # p = J^T P  ->  P = J^-T p

    # zeta = beta0 tau, so the zeta increment is beta0 (P . dg/dp_tau).
    derived = beta0 * (big_p[0] * sp.diff(gx, ptau) + big_p[1] * sp.diff(gy, ptau))
    shipped = (1 + beta0 * ptau) * rpp**3 * (big_p[0] * fx + big_p[1] * fy)
    assert sp.simplify(derived - shipped) == 0

    # and the code's hypot form of E/E0 is that same 1 + beta0 p_tau, numerically
    for gamma0 in (1.5, 20.0):
        r = ReferenceParticle.from_gamma(MASS0, gamma0)
        for d in (-0.02, 0.0, 0.03):
            e_over_e0 = np.hypot(r.momentum_eV * (1 + d), r.mass_eV) / r.total_energy_eV
            ptau_num = (e_over_e0 - 1.0) / r.beta0
            assert e_over_e0 == pytest.approx(1 + r.beta0 * ptau_num, rel=1e-15)


# ---------------------------------------------------------------------------
# The limits, and the structural gates that are deliberately weak
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("state", STATES)
def test_zero_gradient_is_the_identity_bit_for_bit(state: np.ndarray, ref) -> None:
    """``k1 = 0`` returns the input unchanged — no rounding, no branchless arithmetic."""
    for exit_face in (False, True):
        assert np.array_equal(multipole_fringe_map(state, 0.0, ref, exit_face=exit_face), state)
    assert np.array_equal(
        Quadrupole(0.6, 0.0, fringe=True).track(state, ref),
        Quadrupole(0.6, 0.0).track(state, ref),
    )


def test_the_approach_to_the_identity_is_linear_in_k1(ref) -> None:
    """Slope **exactly one**, which is also why this gate cannot see the ``1/12``.

    P2 (ii)'s short-circuit and P2 (iv)'s ``k1 -> 0`` limit both turned on gating the
    *approach* rather than only the endpoint, so it is asserted here too. What it buys is
    the absence of a discontinuity at zero; what it explicitly does **not** buy is the
    coefficient, since a map scaled by any constant has the same unit slope.
    """
    state = STATES[0]
    base = np.abs(multipole_fringe_map(state, 1.0, ref) - state).max()
    for k1 in (1e-2, 1e-3, 1e-4):
        got = np.abs(multipole_fringe_map(state, k1, ref) - state).max()
        assert got == pytest.approx(k1 * base, rel=1e-12)


def test_the_effect_is_cubic_in_the_amplitude(ref) -> None:
    """Order **three**, measured as an order and not as a tolerance — J2/J3's rule.

    A cubic map mis-scaled by a constant is invisible to this too; what it catches is a
    map that picked up a linear or quadratic term, which is the failure that would move
    ``matrix`` or the second-order map underneath the next test.
    """
    state = STATES[0].copy()
    ratios = []
    prev = None
    for scale in (1.0, 0.5, 0.25, 0.125):
        st = state * scale
        st[DELTA] = state[DELTA]  # delta is not an amplitude here
        size = np.abs(multipole_fringe_map(st, 1.7, ref)[[X, PX, Y, PY]] - st[[X, PX, Y, PY]]).max()
        if prev is not None:
            ratios.append(prev / size)
        prev = size
    assert all(r == pytest.approx(8.0, rel=1e-6) for r in ratios), ratios


def test_no_first_or_second_order_quantity_moves(ref) -> None:
    r"""The pre-committed gate: a cubic map must not reach ``matrix``, the tunes or ``T``.

    Asserted, not hoped. ``matrix`` and the Twiss are compared **bit for bit**; the
    second-order map to ``1e-15``, which is a finite-difference floor and not a tolerance
    on physics — ``taylor_expand`` differences the tracked map numerically.

    This is also the statement that MAD-X's ``sectormap`` and PTC at ``no = 2`` cannot
    arbitrate this milestone: they would see exactly the zero on the right-hand side.
    """
    plain = [Drift(0.4), Quadrupole(0.6, 1.3), Drift(0.4), Quadrupole(0.6, -1.3)]
    fringed = [
        Drift(0.4),
        Quadrupole(0.6, 1.3, fringe=True),
        Drift(0.4),
        Quadrupole(0.6, -1.3, fringe=True),
    ]
    lat_a, lat_b = Lattice(plain, ref), Lattice(fringed, ref)

    assert np.array_equal(lat_a.one_turn_matrix(), lat_b.one_turn_matrix())
    assert tunes(lat_a) == tunes(lat_b)
    tw_a, tw_b = closed_twiss(lat_a), closed_twiss(lat_b)
    assert tw_a.beta_x == tw_b.beta_x
    assert tw_a.beta_y == tw_b.beta_y

    # The exact statement is on the analytic matrices, and it is bit for bit.
    assert np.array_equal(
        Quadrupole(0.6, 1.3, fringe=True).matrix(ref), Quadrupole(0.6, 1.3).matrix(ref)
    )
    # The *tracked* map says the same thing to a finite-difference floor: a central
    # difference does not cancel a cubic term, it leaves O(step^2) of it in R and O(step)
    # in T, so these are the differencing scheme's residues, not the fringe's.
    q_a = taylor_expand(lambda s: Quadrupole(0.6, 1.3).track(s, ref), np.zeros(DIM))
    q_b = taylor_expand(lambda s: Quadrupole(0.6, 1.3, fringe=True).track(s, ref), np.zeros(DIM))
    np.testing.assert_allclose(q_b.R, q_a.R, rtol=0.0, atol=1e-12)
    np.testing.assert_allclose(q_b.T, q_a.T, rtol=0.0, atol=1e-8)
    # ...and there really is something for the *tracked* map to differ by.
    moved = Quadrupole(0.6, 1.3, fringe=True).track(STATES[0], ref) - Quadrupole(0.6, 1.3).track(
        STATES[0], ref
    )
    assert np.abs(moved).max() > 1e-9


def test_nothing_first_order_moves_on_a_gradient_bend_either(ref) -> None:
    r"""The same gate on the element the refusal was actually on — and it is not the same test.

    ``Quadrupole``'s version above is the easy half: the only new map there is *cubic*, and
    a cubic map cannot reach a linear quantity. A **rotated gradient** bend inserts a
    *quadratic* map into P3 (a)'s composition, and P3 (a)'s headline was precisely that the
    composed face's origin Jacobian **is** :func:`~accsim.elements.dipole._edge_matrix`. So
    the claim being re-made here is that a centred quadratic kick has a zero Jacobian at the
    origin and leaves that identity standing —
    :func:`~accsim.elements.dipole.curvature_sextupole_kick`'s docstring argues exactly
    that, which is the kind of "should" this project measures rather than believes.

    Nothing before P3 (b) could have covered this: the constructor *raised*.
    """
    L, angle, k1, e1, e2 = 1.0, 0.3, 0.4, 0.08, 0.05

    def bend(fringe: bool, sign: float = 1.0) -> Dipole:
        return Dipole(L, angle, k1=sign * k1, e1=e1, e2=e2, fringe=fringe)

    # 1. the element's own linear map, bit for bit
    assert np.array_equal(bend(True).matrix(ref), bend(False).matrix(ref))

    # 2. and every optics quantity a ring of them reports. The gradient has to alternate
    #    -- a ring of like-signed combined bends is vertically unstable, and an
    #    UnstableLatticeError would have made this gate pass by never running.
    def ring(fringe: bool) -> Lattice:
        return Lattice([bend(fringe, +1.0), Drift(0.5), bend(fringe, -1.0), Drift(0.5)] * 2, ref)

    off, on = ring(False), ring(True)
    assert np.array_equal(off.one_turn_matrix(), on.one_turn_matrix())
    assert tunes(off) == tunes(on)
    tw_off, tw_on = closed_twiss(off), closed_twiss(on)
    assert tw_off.beta_x == tw_on.beta_x
    assert tw_off.beta_y == tw_on.beta_y
    assert natural_chromaticity(off) == natural_chromaticity(on)

    # 3. matrix() is still the origin Jacobian of track(), and the residual is the
    #    finite-difference floor rather than a physical gap: it falls with the step.
    fringed = bend(True)
    residuals = [
        float(
            np.abs(
                jacobian(lambda s: fringed.track(s, ref), np.zeros(DIM), h) - fringed.matrix(ref)
            ).max()
        )
        for h in (1e-4, 1e-5)
    ]
    assert residuals[1] < residuals[0]
    assert residuals[1] < 1e-9

    # 4. ...and the face is emphatically doing something to the *tracked* state.
    assert np.abs(fringed.track(STATES[0], ref) - bend(False).track(STATES[0], ref)).max() > 1e-6


# ---------------------------------------------------------------------------
# One face at a time, and the composition
# ---------------------------------------------------------------------------


def test_the_two_faces_are_distinguishable_and_do_not_cancel(ref) -> None:
    """An exit-sign slip is self-cancelling in a two-face element; isolate the faces.

    The entrance and the exit are each other's inverse *only* at the same point — so
    ``exit . entry`` is the identity for a zero-length element and is emphatically not
    once a body sits between them. Both statements are asserted, because the first is what
    makes a sign error hide and the second is what exposes it.
    """
    state = STATES[0]
    entry = multipole_fringe_map(state, 1.7, ref, exit_face=False)
    exit_ = multipole_fringe_map(state, 1.7, ref, exit_face=True)
    assert np.abs(entry - exit_).max() > 1e-9

    # back-to-back, with nothing in between: the two faces undo each other
    both = multipole_fringe_map(entry, 1.7, ref, exit_face=True)
    assert np.abs(both - state).max() < 1e-14

    # with a body in between they do not, and that is what tracking gates
    q = Quadrupole(0.6, 1.3, fringe=True)
    assert np.abs(q.track(state, ref) - Quadrupole(0.6, 1.3).track(state, ref)).max() > 1e-9


@pytest.mark.parametrize("state", STATES)
def test_the_gradient_free_face_is_untouched_bit_for_bit(state: np.ndarray, ref) -> None:
    r"""P2 (i)'s and P3 (a)'s face, byte-identical with the two new maps composed in.

    The new maps' ``k1 = 0`` identity is necessary but not sufficient — the *composition*
    could still have shifted, which is what this asserts. ``Dipole(fringe=True)`` on a
    gradient-free bend must still be exactly ``wedge(-e, h) . fringe(h) . wedge(e, 0)``,
    built here by hand rather than read back from the element.
    """
    h, e1, e2 = 0.3 / 1.0, 0.08, 0.05
    bend = Dipole(1.0, 0.3, e1=e1, e2=e2, fringe=True)

    got_entry = bend._face(state, e1, ref, bend.k1, exit_face=False)
    want_entry = wedge_map(
        hard_edge_fringe_map(wedge_map(state, e1, 0.0, ref), h, ref), -e1, h, ref
    )
    assert np.array_equal(got_entry, want_entry)

    got_exit = bend._face(state, e2, ref, bend.k1, exit_face=True)
    want_exit = wedge_map(
        hard_edge_fringe_map(wedge_map(state, -e2, h, ref), -h, ref), e2, 0.0, ref
    )
    assert np.array_equal(got_exit, want_exit)


# ---------------------------------------------------------------------------
# The quadrupole wedge — the other, quadratic, half of a rotated gradient face
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("state", STATES)
def test_the_quad_wedge_is_the_curvature_sextupole_kick(state: np.ndarray) -> None:
    r"""The same expression, and the reason is physical, not numerological.

    Both are the quadrupole potential integrated over a path length that varies linearly
    in ``x``: the body's ``(1 + h x)`` metric factor over ``L`` gives ``h k1 L``, the
    wedge's geometric sliver ``x tan(e)`` gives ``k1 theta``. A bend's ``theta = h L``, so
    the two integrated strengths are one expression. Asserted rather than assumed — the
    advisorial worry is exactly that two maps of the same *shape* get merged when their
    strengths happen to coincide in one element and not in another.
    """
    for theta, k1 in ((0.08, 1.3), (-0.05, 0.4), (0.2, -2.0)):
        assert np.array_equal(
            quad_wedge_map(state, theta, k1), curvature_sextupole_kick(state, k1 * theta)
        )
    assert np.array_equal(quad_wedge_map(state, 0.0, 1.3), state)
    assert np.array_equal(quad_wedge_map(state, 0.08, 0.0), state)


def test_the_quad_wedge_is_the_one_piece_that_moves_the_second_order_map(ref) -> None:
    r"""Quadratic, not cubic — so ``T`` *does* move, and only on a **rotated** face.

    The comparison has to be **face against face**, not bend against bend: P2 (i)'s dipole
    fringe already moves ``T`` by ``0.19`` on this magnet, so ``fringe=True`` versus
    ``fringe=False`` would drown the gradient's share entirely. Against the same face with
    the two gradient maps left out:

    - at ``e = 0`` the gap is the finite-difference floor — the multipole fringe is cubic
      and reaches ``T`` not at all, which is the pre-committed gate and the reason
      ``sectormap`` and PTC at ``no = 2`` are vacuous here;
    - at ``e != 0`` it is the wedge's own entries, ``k1 theta`` split ``2:-1`` by Maxwell.
    """
    L, angle, k1 = 1.0, 0.3, 0.4
    h = angle / L

    def _face_T(e: float, *, gradient: bool) -> np.ndarray:
        def face(st: np.ndarray) -> np.ndarray:
            out = wedge_map(st, e, 0.0, ref)
            out = hard_edge_fringe_map(out, h, ref)
            if gradient:
                out = multipole_fringe_map(out, k1, ref, exit_face=False)
                out = quad_wedge_map(out, -e, k1)
            return wedge_map(out, -e, h, ref)

        return taylor_expand(face, np.zeros(DIM)).T

    sector_gap = _face_T(0.0, gradient=True) - _face_T(0.0, gradient=False)
    assert np.abs(sector_gap).max() < 1e-9, "a cubic face must not reach T"

    rotated_gap = _face_T(0.08, gradient=True) - _face_T(0.08, gradient=False)
    assert np.abs(rotated_gap).max() > 1e-3, "the quad wedge must reach T"

    # ...and the entries it lands on are the wedge's own, entry for entry.
    theta = -0.08
    wedge_only = taylor_expand(lambda s: quad_wedge_map(s, theta, k1), np.zeros(DIM))
    assert wedge_only.T[PX, X, X] == pytest.approx(-k1 * theta, rel=1e-6)
    assert wedge_only.T[PX, Y, Y] == pytest.approx(k1 * theta / 2.0, rel=1e-6)
    assert wedge_only.T[PY, X, Y] == pytest.approx(k1 * theta / 2.0, rel=1e-6)


# ---------------------------------------------------------------------------
# Housekeeping
# ---------------------------------------------------------------------------


def test_a_bunch_takes_the_same_path_as_a_particle(ref) -> None:
    """Vectorised over a trailing particle axis, like every other map in the package."""
    bunch = np.stack(STATES, axis=1)
    got = multipole_fringe_map(bunch, 1.7, ref, exit_face=False)
    for i, st in enumerate(STATES):
        np.testing.assert_array_equal(got[:, i], multipole_fringe_map(st, 1.7, ref))

    q = Quadrupole(0.6, 1.3, fringe=True)
    got = q.track(bunch, ref)
    for i, st in enumerate(STATES):
        np.testing.assert_allclose(got[:, i], q.track(st, ref), rtol=0.0, atol=0.0)


def test_the_flag_shows_up_in_the_repr() -> None:
    assert "fringe=True" in repr(Quadrupole(0.6, 1.3, fringe=True))
    assert "fringe" not in repr(Quadrupole(0.6, 1.3))
