r"""P2 (i) — the hard-edge dipole fringe, the second-order map of a field that stops.

A sector bend's body field does not depend on ``y``, so nothing in the linear matrix and
nothing in the exact circle of L3 couples the planes. That is a statement about the
*inside* of the magnet. At the face the field stops, and ``curl B = 0`` will not let it
stop only in ``B_y``: a longitudinal component ``B_s = y dB_y/ds`` appears — a delta
function at a hard edge — whose impulse is a **vertical** kick proportional to the
*horizontal* angle. Every entry the fringe adds to the second-order map therefore
carries a ``y``, in a magnet that bends horizontally, which is exactly the signature P1
measured against MAD-X before any of this was written.

**What is derived here and what is imported.** The map is generated by

    Phi(px, py, delta) = h px pz / ((1 + delta)^2 - px^2),
    W = -Phi(p) ybar^2 / 2,

so the three gradients of ``Phi`` *are* the map, and they are re-derived here with sympy
from ``Phi`` alone and compared against the closed forms
:func:`~accsim.elements.dipole.hard_edge_fringe_map` evaluates — the project's rule that
a coefficient is derived, not recalled. The five entries MAD-X's ``sectormap`` pins are
then re-derived a second way, by composing the fringe's own ``T`` with the body's ``R``
under P1's rule, and the *whole* ``6x6x6`` gap is checked that way, not only the five:
the probe that opened this milestone found **twelve** distinct nonzero entries, of which
P1 had named five.

**The gate the reference legs cannot supply.** ``zeta``'s share of the fringe is
``Phi_delta ybar^2``, which is *cubic*, so it is absent from ``T`` — MAD-X's
``sectormap``, PTC's ``maptable`` and the five pinned entries are all blind to it. What
is not blind to it is **symplecticity**: ``x``'s dependence on ``delta`` and ``zeta``'s
on ``px`` are conjugate halves of the same generating function, so the ``beta0/beta``
conversion between ``tau`` and ``zeta`` is gated exactly once, by
:func:`~accsim.symplectic.is_symplectic_map_canonical`. That is asserted here both ways:
the map passes, and a variant with the conversion dropped fails.
"""

from __future__ import annotations

import numpy as np
import pytest
import sympy as sp

from accsim import (
    Dipole,
    Drift,
    Lattice,
    Quadrupole,
    ReferenceParticle,
    TaylorMap,
    closed_twiss,
    compose,
    is_symplectic_map_canonical,
    jacobian,
    natural_chromaticity,
    taylor_expand,
    tunes,
)
from accsim.coords import DELTA, DIM, PX, PY, ZETA, X, Y
from accsim.elements.dipole import hard_edge_fringe_map

MASS0, GAMMA0 = 938.27208816e6, 20.0
L_B, ANGLE = 1.0, 0.1
H = ANGLE / L_B

#: Amplitudes with every coordinate live at once. A fringe entry is a *product* of two
#: coordinates, so a state with a zero in it cannot separate one from another.
STATES = [
    np.array([1.3e-3, 7.0e-4, -9.0e-4, 5.0e-4, 2.0e-3, 4.0e-3]),
    np.array([-2.0e-3, 3.0e-3, 4.0e-3, -1.5e-3, -1.0e-3, -2.0e-2]),
    np.array([5.0e-3, -8.0e-3, 6.0e-3, 9.0e-3, 3.0e-3, 5.0e-2]),
]


@pytest.fixture
def ref() -> ReferenceParticle:
    return ReferenceParticle.from_gamma(MASS0, GAMMA0)


# ---------------------------------------------------------------------------
# The generator, and the three gradients that *are* the map
# ---------------------------------------------------------------------------


def _symbolic_phi():
    """``Phi`` and its three gradients, from sympy, sharing no arithmetic with the code."""
    px, py, d, h = sp.symbols("px py delta h", real=True)
    pz = sp.sqrt((1 + d) ** 2 - px**2 - py**2)
    phi = h * px * pz / ((1 + d) ** 2 - px**2)
    return (px, py, d, h), phi, (sp.diff(phi, px), sp.diff(phi, py), sp.diff(phi, d))


def test_the_coded_gradients_are_the_gradients_of_the_generator() -> None:
    r"""``dPhi/dpx``, ``dPhi/dpy``, ``dPhi/ddelta`` — sympy against the coded closed forms.

    The implementation does not differentiate anything at run time; it evaluates three
    hand-rearranged expressions, chosen so that no term is a cancelling difference for a
    beam-like particle (``pz^2 - px^2`` and ``py^2 - pz^2`` are both ~1, not ~0). Those
    rearrangements are exactly where a factor goes missing, so they are checked against
    ``sympy.diff`` of the generator itself and asserted **identically zero**, not to a
    tolerance.
    """
    (px, py, d, h), phi, (d_px, d_py, d_d) = _symbolic_phi()
    pz = sp.sqrt((1 + d) ** 2 - px**2 - py**2)
    den = (1 + d) ** 2 - px**2  # = pz^2 + py^2

    coded = {
        "px": h * ((pz**2 - px**2) / (pz * den) + 2 * px**2 * pz / den**2),
        "py": -h * px * py / (pz * den),
        "delta": h * px * (1 + d) * (py**2 - pz**2) / (pz * den**2),
    }
    for name, exact in (("px", d_px), ("py", d_py), ("delta", d_d)):
        assert sp.simplify(coded[name] - exact) == 0, name

    # And the one value the whole effect is proportional to: at the origin the only
    # surviving gradient is dPhi/dpx = h, which is why T[x, y, y] is h/2 and nothing else.
    at0 = {px: 0, py: 0, d: 0}
    assert sp.simplify(phi.subs(at0)) == 0
    assert sp.simplify(d_px.subs(at0)) == h
    assert sp.simplify(d_py.subs(at0)) == 0
    assert sp.simplify(d_d.subs(at0)) == 0


def test_one_face_has_exactly_three_second_order_entries(ref: ReferenceParticle) -> None:
    r"""The fringe's own ``T``: ``T[x,y,y] = h/2``, ``T[py,px,y] = T[py,y,px] = -h/2``.

    Everything else in the ``6x6x6`` is zero, and the linear map is the identity — the
    two facts that together say the fringe is a purely second-order-and-up object. The
    exit face is the same map at ``-h``, because the field switches *off* there.
    """
    for sign in (+1.0, -1.0):
        h = sign * H
        got = taylor_expand(lambda s, h=h: hard_edge_fringe_map(s, h, ref), np.zeros(DIM))
        np.testing.assert_allclose(got.R, np.eye(DIM), atol=1e-11)
        np.testing.assert_allclose(got.k, np.zeros(DIM), atol=1e-14)

        want = np.zeros((DIM,) * 3)
        want[X, Y, Y] = h / 2
        want[PY, PX, Y] = want[PY, Y, PX] = -h / 2
        np.testing.assert_allclose(got.T, want, atol=1e-11)


# ---------------------------------------------------------------------------
# The composed bend: all 216 entries, and the five MAD-X pinned by name
# ---------------------------------------------------------------------------


def _fringe_map(h: float) -> TaylorMap:
    """The face's second-order map as a :class:`TaylorMap`, written from the generator."""
    T = np.zeros((DIM,) * 3)
    T[X, Y, Y] = h / 2
    T[PY, PX, Y] = T[PY, Y, PX] = -h / 2
    return TaylorMap(np.zeros(DIM), np.zeros(DIM), np.eye(DIM), T)


def test_the_whole_gap_is_the_two_faces_composed_with_the_body(ref: ReferenceParticle) -> None:
    r"""``fringe(-h) . body . fringe(h)``, entry for entry over all 216 — not only the five.

    P1 measured the gap against MAD-X and named the five entries that were large. The
    gap is bigger than that: twelve distinct entries are nonzero, including a
    ``T[zeta, y, y]`` (the body transporting the entrance face's ``x`` shift into the
    path length) and a ``T[py, y, delta]`` that no closed form in the roadmap mentions.
    Composing the face's three-entry ``T`` with the *tracked* body under P1's
    :func:`~accsim.taylor.compose` predicts every one of them, so this is the gate that
    cannot be passed by getting five numbers right.
    """
    plain, fringed = Dipole(L_B, ANGLE), Dipole(L_B, ANGLE, fringe=True)
    body = taylor_expand(lambda s: plain.track(s, ref), np.zeros(DIM))
    got = taylor_expand(lambda s: fringed.track(s, ref), np.zeros(DIM))
    want = compose(_fringe_map(-H), compose(body, _fringe_map(H)))

    np.testing.assert_allclose(got.R, want.R, atol=1e-11)
    np.testing.assert_allclose(got.T, want.T, atol=1e-10)

    # And the gap is not small: twelve distinct entries, the largest ~h L / 2.
    gap = got.T - body.T
    assert np.max(np.abs(gap)) == pytest.approx(H * L_B / 2, rel=1e-3)
    upper = np.array([gap[i, j, k] for i in range(DIM) for j in range(DIM) for k in range(j, DIM)])
    assert np.count_nonzero(np.abs(upper) > 1e-9) == 12


def test_the_five_entries_madx_pins_are_these_closed_forms(ref: ReferenceParticle) -> None:
    r"""The five in ``tests/reference/test_second_order_map_madx.py``, re-derived by hand.

    Independent of :func:`~accsim.taylor.compose`: with ``R`` the body's linear matrix
    and the face's ``T`` above, the composed second order is
    ``sum_a R_ia T^ent_ajk + sum_ab T^exit_iab R_aj R_bk``, and evaluating that by hand
    on a pure sector bend gives

        T[x, y, py] = R[x, py] * (-h/2) * 2 / 2 = -h L / 2          (entrance, through the body)
        T[y, px, y] = R[y, py] * (-h/2)         = -h L / 2
        T[py, px, py] = (+h/2) * R[px,px] R[y,py] = +h L cos(theta) / 2   (exit, on the body's image)
        T[x, y, y]  = R[x, x] (h/2) - (h/2) R[y,y]^2 = -h (1 - cos theta) / 2
        T[px, y, y] = R[px, x] (h/2)                = -h^2 sin(theta) / 2

    — the entrance face's ``y``-kick carried through the body's *vertical drift* in the
    first two, and the exit face acting on the body's image in the third. The last two
    are the two faces' ``x`` shifts nearly cancelling, which is why they are down by
    ``theta`` on the others.
    """
    plain, fringed = Dipole(L_B, ANGLE), Dipole(L_B, ANGLE, fringe=True)
    gap = (
        taylor_expand(lambda s: fringed.track(s, ref), np.zeros(DIM)).T
        - taylor_expand(lambda s: plain.track(s, ref), np.zeros(DIM)).T
    )
    c, s = np.cos(ANGLE), np.sin(ANGLE)
    assert gap[X, Y, PY] == pytest.approx(-H * L_B / 2, abs=1e-10)
    assert gap[Y, PX, Y] == pytest.approx(-H * L_B / 2, abs=1e-10)
    assert gap[PY, PX, PY] == pytest.approx(+H * L_B * c / 2, abs=1e-10)
    assert gap[X, Y, Y] == pytest.approx(-H * (1.0 - c) / 2, abs=1e-10)
    assert gap[PX, Y, Y] == pytest.approx(-H * H * s / 2, abs=1e-10)

    # The horizontal-only block stays empty: at this order the fringe is a y-effect.
    assert np.max(np.abs(gap[np.ix_([X, PX], [X, PX], [X, PX])])) < 1e-10


# ---------------------------------------------------------------------------
# Symplecticity — the only gate on the longitudinal half
# ---------------------------------------------------------------------------


def _fringe_without_the_time_conversion(state: np.ndarray, h: float, ref: ReferenceParticle):
    """The same map with ``zeta``'s ``beta0/beta`` factor dropped — deliberately wrong."""
    st = np.asarray(state, dtype=float)
    out = hard_edge_fringe_map(st, h, ref)
    one_plus = 1.0 + st[DELTA]
    e_over_e0 = np.hypot(ref.momentum_eV * one_plus, ref.mass_eV) / ref.total_energy_eV
    out[ZETA] = st[ZETA] + (out[ZETA] - st[ZETA]) * one_plus / e_over_e0
    return out


def _fringe_as_a_transverse_effect(state: np.ndarray, h: float, ref: ReferenceParticle):
    """The same map with ``zeta`` left alone entirely — the obvious wrong reading."""
    st = np.asarray(state, dtype=float)
    out = hard_edge_fringe_map(st, h, ref)
    out[ZETA] = st[ZETA]
    return out


@pytest.mark.parametrize("state", STATES)
def test_the_map_is_exactly_symplectic_because_it_is_generated(
    state: np.ndarray, ref: ReferenceParticle
) -> None:
    """One face, and the whole bend, symplectic in the canonical pair at finite amplitude.

    A generating function gives symplecticity at *every* amplitude rather than to the
    order the map is written, so this is asserted at ``delta`` up to 5% and millimetre
    coordinates, not only near the origin.
    """
    assert is_symplectic_map_canonical(lambda s: hard_edge_fringe_map(s, H, ref), state, ref)
    assert is_symplectic_map_canonical(lambda s: hard_edge_fringe_map(s, -H, ref), state, ref)
    bend = Dipole(L_B, ANGLE, fringe=True)
    assert is_symplectic_map_canonical(lambda s: bend.track(s, ref), state, ref)


def test_symplecticity_is_the_only_gate_on_the_longitudinal_half(ref: ReferenceParticle) -> None:
    r"""``zeta``'s share is cubic — invisible to ``T`` — and only symplecticity sees it.

    ``zeta`` picks up ``(1/2) (beta0/beta) (dPhi/ddelta) ybar^2``, a product of three
    coordinates, so it contributes nothing to the second-order map and neither MAD-X's
    ``sectormap`` nor PTC's ``maptable`` can see it: both wrong variants below have the
    **same** ``T`` as the shipped map, to ``1e-12``. It is not free, though — it is the
    conjugate partner of ``x``'s dependence on ``delta`` — so a map that leaves ``zeta``
    alone is not symplectic, and is rejected here by ``4.4e-6``, four thousand times the
    tolerance.
    """
    state = STATES[2]
    assert is_symplectic_map_canonical(lambda s: hard_edge_fringe_map(s, H, ref), state, ref)
    assert not is_symplectic_map_canonical(
        lambda s: _fringe_as_a_transverse_effect(s, H, ref), state, ref
    )
    for variant in (_fringe_as_a_transverse_effect, _fringe_without_the_time_conversion):
        bad = taylor_expand(lambda s, v=variant: v(s, H, ref), np.zeros(DIM))
        good = taylor_expand(lambda s: hard_edge_fringe_map(s, H, ref), np.zeros(DIM))
        np.testing.assert_allclose(good.T, bad.T, atol=1e-12)


def test_the_beta0_over_beta_factor_is_gated_only_at_low_energy() -> None:
    r"""And the ``beta0/beta`` conversion inside it is a **low-energy** gate, stated as such.

    ``zeta = beta0 tau`` while the generating function lives in ``tau``, so the ``zeta``
    term carries ``beta0/beta = (E/E0)/(1 + delta)``. That factor tends to ``1`` as the
    beam becomes ultrarelativistic, and so does the symplecticity error of dropping it:
    measured ``9.1e-8`` at ``gamma0 = 1.5`` and ``2.3e-8`` at ``3``, but ``5.1e-10`` at
    the ``gamma0 = 20`` the rest of this suite runs at — *below* the ``1e-9`` tolerance,
    and ``4.6e-12`` at ``200``. So the factor is real and it is checked, but only a
    low-energy fixture can check it; at 20 GeV nothing in the package can tell the two
    apart. Recorded rather than papered over.
    """
    state = STATES[2]
    for gamma0, caught in ((1.5, True), (3.0, True), (20.0, False), (200.0, False)):
        ref = ReferenceParticle.from_gamma(MASS0, gamma0)
        assert is_symplectic_map_canonical(
            lambda s, r=ref: hard_edge_fringe_map(s, H, r), state, ref
        )
        seen = not is_symplectic_map_canonical(
            lambda s, r=ref: _fringe_without_the_time_conversion(s, H, r), state, ref
        )
        assert seen is caught, gamma0


def test_the_two_faces_undo_each_other_to_fourth_order_and_not_beyond(
    ref: ReferenceParticle,
) -> None:
    r"""``fringe(-h) . fringe(h)`` is the identity through **fourth** order, and no further.

    A zero-length bend is no magnet at all, so the two faces at the same point ought to
    compose to nothing — and to fourth order they do. They are not inverses *by
    construction*, though, and the reason is worth naming: the gradients of ``Phi`` are
    evaluated at the **incoming** momenta, and ``py`` is not the same on the two sides,
    so the exit face reads ``dPhi/dpy`` at a point the entrance face has already moved.

    The leftover is fifth order and its leading term is exact:

        x  :  -h^2 px py y^3 / (1 + delta)^4          (measured ratio 1.0000)
        py : +3 h^2 px^2 py y^2 / (2 (1 + delta)^4)

    so the gate is the **order** and a *ratio*, never a tolerance — a bare
    ``approx(..., rel=...)`` is vacuous down here, where every number is below pytest's
    ``1e-12`` absolute floor. Halving every coordinate must divide the residual by
    ``2^5``, and it does (fitted exponent ``4.9``). A transcription error in any of the
    three gradients would surface as a *lower* power, not as a bigger number. This is a
    property of the PTC/MAD-NG hard-edge form that both arbiters share, not of the
    transcription of it, and at ``1e-13`` it is three orders below anything ``T`` or the
    reference legs resolve.
    """
    base = STATES[2]
    scales = np.array([1.0, 0.5, 0.25, 0.125])
    residuals = np.array(
        [
            np.max(
                np.abs(
                    hard_edge_fringe_map(hard_edge_fringe_map(base * s, H, ref), -H, ref) - base * s
                )
            )
            for s in scales
        ]
    )
    order = np.polyfit(np.log(scales), np.log(residuals), 1)[0]
    assert order == pytest.approx(5.0, abs=0.2), order

    # The leading coefficients, as ratios so nothing is compared against a floor.
    px, py, y, one_plus = base[PX], base[PY], base[Y], 1.0 + base[DELTA]
    got = hard_edge_fringe_map(hard_edge_fringe_map(base, H, ref), -H, ref) - base
    assert got[X] / (-(H**2) * px * py * y**3 / one_plus**4) == pytest.approx(1.0, rel=1e-3)
    assert got[PY] / (1.5 * H**2 * px**2 * py * y**2 / one_plus**4) == pytest.approx(1.0, rel=1e-3)


# ---------------------------------------------------------------------------
# What it must NOT change
# ---------------------------------------------------------------------------


def _ring(ref: ReferenceParticle, *, fringe: bool) -> Lattice:
    cell = [
        Quadrupole(0.3, 1.2),
        Drift(0.5),
        Dipole(L_B, ANGLE, fringe=fringe),
        Quadrupole(0.3, -1.2),
        Drift(0.5),
    ]
    return Lattice(cell * 8, ref)


def test_the_origin_jacobian_is_the_identity_so_no_optics_moves(ref: ReferenceParticle) -> None:
    r"""Every first-order quantity in the package is **bit-identical** with the fringe on.

    The fringe's terms are all quadratic (``ybar^2``, and ``Phi ybar`` with ``Phi(0) =
    0``), so its Jacobian at the origin is the identity — not merely close to it. That
    makes the claim exact rather than tolerated: ``matrix``, the tunes, ``beta``, the
    dispersion and the natural chromaticity of a ring are the *same floats*. It is also
    why P1 was needed to find the gap at all: no first-order cross-check could.
    """
    J = jacobian(lambda s: hard_edge_fringe_map(s, H, ref), np.zeros(DIM), 1e-6)
    np.testing.assert_allclose(J, np.eye(DIM), atol=1e-12)

    plain, fringed = Dipole(L_B, ANGLE), Dipole(L_B, ANGLE, fringe=True)
    assert np.array_equal(plain.matrix(ref), fringed.matrix(ref))

    off, on = _ring(ref, fringe=False), _ring(ref, fringe=True)
    t_off, t_on = closed_twiss(off), closed_twiss(on)
    assert np.array_equal(t_off.beta_x, t_on.beta_x)
    assert np.array_equal(t_off.beta_y, t_on.beta_y)
    assert np.array_equal(t_off.disp_x, t_on.disp_x)
    assert tunes(off) == tunes(on)
    assert natural_chromaticity(off) == natural_chromaticity(on)


def test_fringe_off_is_the_shipped_bend_bit_for_bit(ref: ReferenceParticle) -> None:
    """The default is unchanged — a whole bunch through both maps, ``array_equal``."""
    rng = np.random.default_rng(20260903)
    bunch = rng.normal(scale=2.0e-3, size=(DIM, 128))
    assert np.array_equal(
        Dipole(L_B, ANGLE).track(bunch, ref), Dipole(L_B, ANGLE, fringe=False).track(bunch, ref)
    )
    # ...and the combined-function branch too, which the fringe is refused on anyway.
    assert np.array_equal(
        Dipole(L_B, ANGLE, k1=0.4).track(bunch, ref),
        Dipole(L_B, ANGLE, k1=0.4, fringe=False).track(bunch, ref),
    )


def test_it_is_the_field_stopping_so_it_vanishes_with_y_or_with_h(ref: ReferenceParticle) -> None:
    r"""No ``y``, no fringe; no bend, no fringe — both exactly, at any angle or momentum.

    The kick is ``B_s = y dB_y/ds`` integrated across the face, so a particle in the
    median plane sees nothing however steeply it is going, and a straight "bend" has no
    ``dB_y/ds`` to terminate. Both are identities in the arithmetic, not limits.
    """
    for state in STATES:
        flat = state.copy()
        flat[Y] = 0.0
        assert np.array_equal(hard_edge_fringe_map(flat, H, ref), flat)
        assert np.array_equal(hard_edge_fringe_map(state, 0.0, ref), state)
    straight = Dipole(2.0, 0.0, fringe=True)
    rng = np.random.default_rng(5)
    bunch = rng.normal(scale=1e-3, size=(DIM, 32))
    assert np.array_equal(straight.track(bunch, ref), Dipole(2.0, 0.0).track(bunch, ref))


def test_a_rotated_or_gradient_face_is_refused_rather_than_half_applied() -> None:
    r"""``e1``/``e2`` need the wedge and ``k1`` needs the multipole fringe; neither exists.

    The refusal is the point, not a limitation to be worked around: a rotated face's
    nonlinear map is the fringe **plus** a wedge, and the wedge is first order in the
    face angle where the fringe is second — so applying only the fringe on a rectangular
    bend would be *further* from MAD-X than applying neither. Same shape as the bending
    dipole's refusal to be displaced (K1).
    """
    for kwargs in ({"e1": 0.05}, {"e2": 0.05}, {"e1": 0.05, "e2": 0.05}, {"k1": 0.3}):
        with pytest.raises(NotImplementedError, match="pure sector face"):
            Dipole(L_B, ANGLE, fringe=True, **kwargs)
    # ...and each is legal without the fringe, and legal with the fringe when zero.
    Dipole(L_B, ANGLE, e1=0.05, e2=0.05, k1=0.3)
    Dipole(L_B, ANGLE, e1=0.0, k1=0.0, fringe=True)


def test_the_repr_says_so(ref: ReferenceParticle) -> None:
    """A bend that tracks differently must not print the same as one that does not."""
    assert "fringe=True" in repr(Dipole(L_B, ANGLE, fringe=True))
    assert "fringe" not in repr(Dipole(L_B, ANGLE))
