/*
 * Bundled scenarios for the accsim editor. GENERATED by scripts/make_presets.py —
 * edit that script, not this file. Plain JSON after the assignment, so
 * accsim.scenario (Python) and tests/analytic/test_scenario.py read it too: they
 * take the text after 'ACCSIM_PRESETS = ' up to the closing '];'.
 */
var ACCSIM_PRESETS = [
 {
  "format": "accsim-scenario/1",
  "id": "fodo-cell",
  "name": "FODO cell",
  "description": "One symmetric cell of a 10 GeV proton synchrotron: half a focusing quadrupole, a sector bend, a defocusing quadrupole, a second bend, and the other half of the focusing quadrupole. 24 of these close a ring.",
  "periodic": true,
  "reference": {
   "species": "proton",
   "energy_mode": "total",
   "energy_eV": 10000000000.0
  },
  "beam": {
   "emit_x": 2e-06,
   "emit_y": 2e-06,
   "sigma_delta": 0.0005
  },
  "elements": [
   {
    "type": "Quadrupole",
    "name": "QF.h",
    "length": 0.25,
    "k1": 0.55
   },
   {
    "type": "Drift",
    "name": "D1",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B1",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D2",
    "length": 1.0
   },
   {
    "type": "Quadrupole",
    "name": "QD",
    "length": 0.5,
    "k1": -0.55
   },
   {
    "type": "Drift",
    "name": "D3",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B2",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D4",
    "length": 1.0
   },
   {
    "type": "Quadrupole",
    "name": "QF.h",
    "length": 0.25,
    "k1": 0.55
   }
  ]
 },
 {
  "format": "accsim-scenario/1",
  "id": "electron-ring",
  "name": "Electron storage ring",
  "description": "The 192 m, 24-cell ring of examples/build_a_machine.py at its 2 GeV store energy: thin quadrupoles, sector bends totalling 2 pi, and one 5 MV cavity on harmonic 400.",
  "periodic": true,
  "reference": {
   "species": "electron",
   "energy_mode": "total",
   "energy_eV": 2000000000.0
  },
  "beam": {
   "emit_x": 5e-08,
   "emit_y": 5e-10,
   "sigma_delta": 0.0007
  },
  "elements": [
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "RFCavity",
    "name": "RF",
    "voltage": 5000000.0,
    "harmonic": 400,
    "phi_s": 0.0
   }
  ]
 },
 {
  "format": "accsim-scenario/1",
  "id": "dba-cell",
  "name": "Double-bend achromat",
  "description": "One cell of a 3 GeV light source: two sector bends with a strong quadrupole between them, tuned so the dispersion closes to zero in the straight where an insertion device would go. Two thin sextupoles at dispersion pull the chromaticity back towards zero.",
  "periodic": true,
  "reference": {
   "species": "electron",
   "energy_mode": "total",
   "energy_eV": 3000000000.0
  },
  "beam": {
   "emit_x": 5e-09,
   "emit_y": 5e-11,
   "sigma_delta": 0.001
  },
  "elements": [
   {
    "type": "Drift",
    "name": "straight",
    "length": 1.5
   },
   {
    "type": "Quadrupole",
    "name": "QD1",
    "length": 0.3,
    "k1": -2.85
   },
   {
    "type": "Drift",
    "name": "D1",
    "length": 0.3
   },
   {
    "type": "Quadrupole",
    "name": "QF1",
    "length": 0.3,
    "k1": 3.75
   },
   {
    "type": "Drift",
    "name": "D2",
    "length": 0.4
   },
   {
    "type": "Dipole",
    "name": "B1",
    "length": 1.0,
    "angle": 0.19634954084936207
   },
   {
    "type": "Drift",
    "name": "D3",
    "length": 0.2
   },
   {
    "type": "ThinSextupole",
    "name": "SD",
    "k2l": -3.0
   },
   {
    "type": "Drift",
    "name": "D4",
    "length": 0.15
   },
   {
    "type": "Quadrupole",
    "name": "QFc",
    "length": 0.3,
    "k1": 7.389543282640958
   },
   {
    "type": "Drift",
    "name": "D4",
    "length": 0.15
   },
   {
    "type": "ThinSextupole",
    "name": "SF",
    "k2l": 6.0
   },
   {
    "type": "Drift",
    "name": "D3",
    "length": 0.2
   },
   {
    "type": "Dipole",
    "name": "B2",
    "length": 1.0,
    "angle": 0.19634954084936207
   },
   {
    "type": "Drift",
    "name": "D2",
    "length": 0.4
   },
   {
    "type": "Quadrupole",
    "name": "QF1",
    "length": 0.3,
    "k1": 3.75
   },
   {
    "type": "Drift",
    "name": "D1",
    "length": 0.3
   },
   {
    "type": "Quadrupole",
    "name": "QD1",
    "length": 0.3,
    "k1": -2.85
   },
   {
    "type": "Drift",
    "name": "straight",
    "length": 1.5
   }
  ]
 },
 {
  "format": "accsim-scenario/1",
  "id": "triplet-line",
  "name": "Quadrupole triplet line",
  "description": "A transfer line, not a ring: the beam enters with a given Twiss, a quadrupole triplet refocuses it, and a small corrector kick shows how a trajectory error grows downstream.",
  "periodic": false,
  "reference": {
   "species": "proton",
   "energy_mode": "kinetic",
   "energy_eV": 1000000000.0
  },
  "initial_twiss": {
   "beta_x": 12.0,
   "alpha_x": 0.0,
   "beta_y": 12.0,
   "alpha_y": 0.0,
   "disp_x": 0.0,
   "disp_px": 0.0
  },
  "beam": {
   "emit_x": 1e-06,
   "emit_y": 1e-06,
   "sigma_delta": 0.001
  },
  "elements": [
   {
    "type": "Drift",
    "name": "D0",
    "length": 3.0
   },
   {
    "type": "Corrector",
    "name": "CH",
    "kick_x": 0.0002,
    "kick_y": 0.0
   },
   {
    "type": "Drift",
    "name": "D1",
    "length": 1.0
   },
   {
    "type": "Quadrupole",
    "name": "Q1",
    "length": 0.5,
    "k1": 0.9
   },
   {
    "type": "Drift",
    "name": "D2",
    "length": 0.4
   },
   {
    "type": "Quadrupole",
    "name": "Q2",
    "length": 0.5,
    "k1": -1.6
   },
   {
    "type": "Drift",
    "name": "D3",
    "length": 0.4
   },
   {
    "type": "Quadrupole",
    "name": "Q3",
    "length": 0.5,
    "k1": 0.9
   },
   {
    "type": "Drift",
    "name": "D4",
    "length": 4.0
   },
   {
    "type": "Aperture",
    "name": "AP",
    "shape": "circular",
    "half_x": 0.02,
    "length": 0.0
   }
  ]
 },
 {
  "format": "accsim-scenario/1",
  "id": "wiggler-ring",
  "name": "Ring with a wiggler",
  "description": "The electron storage ring with a 2 m, 1.5 T wiggler in an added straight. A wiggler focuses vertically and nowhere else: watch beta_y through it.",
  "periodic": true,
  "reference": {
   "species": "electron",
   "energy_mode": "total",
   "energy_eV": 2000000000.0
  },
  "beam": {
   "emit_x": 5e-08,
   "emit_y": 5e-10,
   "sigma_delta": 0.0007
  },
  "elements": [
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "DW",
    "length": 1.0
   },
   {
    "type": "Wiggler",
    "name": "W",
    "period": 0.1,
    "h0": 0.2248,
    "periods": 20
   },
   {
    "type": "Drift",
    "name": "DW",
    "length": 1.0
   },
   {
    "type": "RFCavity",
    "name": "RF",
    "voltage": 5000000.0,
    "harmonic": 408,
    "phi_s": 0.0
   }
  ]
 },
 {
  "format": "accsim-scenario/1",
  "id": "kicked-ring",
  "name": "Displaced quadrupole",
  "description": "The electron storage ring with its first focusing quadrupole pushed 0.5 mm sideways and one horizontal corrector three cells downstream. The closed orbit leaves the design axis; tune the corrector to flatten it.",
  "periodic": true,
  "reference": {
   "species": "electron",
   "energy_mode": "total",
   "energy_eV": 2000000000.0
  },
  "beam": {
   "emit_x": 5e-08,
   "emit_y": 5e-10,
   "sigma_delta": 0.0007
  },
  "elements": [
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666,
    "dx": 0.0005
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Corrector",
    "name": "CH",
    "kick_x": -6e-05,
    "kick_y": 0.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QD",
    "k1l": -0.3333333333333333
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "Dipole",
    "name": "B",
    "length": 2.0,
    "angle": 0.1308996938995747
   },
   {
    "type": "Drift",
    "name": "D",
    "length": 1.0
   },
   {
    "type": "ThinQuadrupole",
    "name": "QF.h",
    "k1l": 0.16666666666666666
   }
  ]
 }
];
if (typeof module === "object" && module.exports) module.exports = ACCSIM_PRESETS;
